[package]
name = "recrust_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
recrust_ast = { path = "../recrust_ast" }
proc-macro2 = "1.0.94"
quote = "1.0.39"
syn = "2.0"
